[package]

name = "acacia"
version = "0.0.1"
authors = ["Eduard Bopp <eduard.bopp@aepsil0n.de>"]

[profile.test]
debug = false

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dev-dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck"

[dev-dependencies.quickcheck_macros]
git = "https://github.com/BurntSushi/quickcheck"
