[package]

name = "acacia"
version = "0.0.1"
authors = ["Eduard Bopp <eduard.bopp@aepsil0n.de>"]

[profile.test]
debug = false

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dev-dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"
features = ["arbitrary"]

[dependencies.itertools]
git = "https://github.com/bluss/rust-itertools"

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
