[package]

name = "gravity"
version = "0.0.1"
authors = ["Eduard Bopp <eduard.bopp@aepsil0n.de>"]

[dependencies.acacia]
path = "../../"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra.git"
